### ISSUE TITLE
Compiling SmartHotels.Services.All fails missing AppSettings files

### ISSUE THREAD

**Issue by sawpresto** [microsoft/SmartHotel360-Backend#12]
When compiling the SmartHotels.Services.All solution in Visual Studio 2017, in the SeedImages folder under the solution file in the Seed.Images project, it looks like a few appsettings files are missing: 

- appsettings.json
- appsettings.k8sdev.json
- appsettings.pmain.json
- appsettings.public.json

```
Error | MSB3030 | Could not copy the file "C:\Temp\SmartHotel360-AKS-DevSpaces-Demo-master\src\SmartHotel360-Azure-backend\src\SmartHotel.Services.Seed.Images\appsettings.pmain.json" because it was not found. | SmartHotel.Services.Seed.Images | C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 4529 |  
```

I checked and the files are missing in the repository. Any ideas on how to solve this?

**Comment by eiximenis** [comment]
Solved in PR #35
