### ISSUE TITLE
Is this the new AKS version of the SH360 backend?

### ISSUE THREAD

**Issue by spacecat** [microsoft/SmartHotel360-Backend#18]
Is this the new AKS version of the SH360 backend? Separate repo?
Where is the ACS one? Repo URL?

**Comment by IoTFier** [comment]
@dasanagu , @eiximenis - can you please help us with this request ?
Also, is there a transition document link to move existing resources from ACS to AKS ? 
Thanks

**Comment by eiximenis** [comment]
Hi!
This is the AKS version. There is no repo with the ACS repo.

@IoTFier I don't know any resource for migrating from ACS to AKS. Maybe @dasanagu could help on this.
