### ISSUE TITLE
Apps failing due to missing Application Insights Resource

### ISSUE THREAD

**Issue by isaac2004** [microsoft/SmartHotel360-Backend#19]
I spun up the AKS instance and noticed I was getting errors on some apps that were suffering 'CrashLoopBackOff' errors while running. 

![image](https://user-images.githubusercontent.com/8878502/46829230-350c6680-cd6b-11e8-951b-1645cdf8cb67.png)

After taking a look at the logs, it seems that there is no Application Insights instrumentation key being passed into these apps, and that is causing failures. 

**Suggestions**

![image](https://user-images.githubusercontent.com/8878502/46829384-a6e4b000-cd6b-11e8-8fa1-c0b093429eec.png)

**Tasks**

![image](https://user-images.githubusercontent.com/8878502/46829421-c976c900-cd6b-11e8-83e4-42e8d14dbd36.png)

**Reviews** 

![image](https://user-images.githubusercontent.com/8878502/46829449-df848980-cd6b-11e8-90a0-d1775aee0a10.png)

Looking at the ARM template, there is no App Insights Resource being created, so no key to pass into the YAML files.

**Comment by bradygmsft** [comment]
@eiximenis could we get this resolved? We should make sure the ARM templates create everything that's needed by the clusterized services.

**Comment by vyunev** [comment]
The error still exists, is there workaround?

**Comment by eiximenis** [comment]
@bradygaster It is not problem about resource missing in ARM template, I think...

Let me review helm charts for those apps...

**Comment by jcorioland** [comment]
I confirm that it works perfectly after adding the instrumentation key (not the id) of application insights in the yaml file pointed by @eiximenis. Thanks!

**Comment by eiximenis** [comment]
Solved in PR #35
