### ISSUE TITLE
incorrect URI in Readme.md for template deployment

### ISSUE THREAD

**Issue by amitpuri** [Microsoft/SmartHotel360-Backend#22]
There was an error loading the template from URI 'https://raw.githubusercontent.com/Microsoft/SmartHotel360-Backend/master/Source/ARM/smarthote360.backend.deployment.json'. Ensure that the template is publicly accessible and does not have any comments.

The URI is https://github.com/Microsoft/SmartHotel360-Backend/blob/master/Source/arm/smarthote360.backend.deployment.json

**Comment by dasanagu** [comment]
Fixed with commit [8bef1b4 ](https://github.com/Microsoft/SmartHotel360-Backend/commit/8bef1b4e7d2acdb27d11e9b42dead8f426a882b2)
