### ISSUE TITLE
helm is not configured to use RBAC, which fails in default AKS 

### ISSUE THREAD

**Issue by squillace** [microsoft/SmartHotel360-Backend#24]
Unless you turn RBAC off on cluster creation, which you shouldn't, the current helm installation in the install scripts will fail. 

https://github.com/Microsoft/SmartHotel360-Backend/blob/8bef1b4e7d2acdb27d11e9b42dead8f426a882b2/Source/setup/01-aks-create.sh#L30

Use the instructions here to update the script; after I do the demo dance here, I'll submit a fix, too. 

https://docs.helm.sh/using_helm/#tiller-and-role-based-access-control

**Comment by eiximenis** [comment]
Solved with PR #35
