### ISSUE TITLE
03.-deploy-web.sh pushed directories that don't exist

### ISSUE THREAD

**Issue by squillace** [microsoft/SmartHotel360-Backend#25]
`pushd ../src/SmartHotel360-public-web/` is a now-unreachable location. So, exactly WHAT is supposed to install the web app at this point?

I can go over to the smarthotel web site, but..... 

https://github.com/Microsoft/SmartHotel360-Backend/blob/8bef1b4e7d2acdb27d11e9b42dead8f426a882b2/Source/setup/03-deploy-web.sh#L132

**Comment by olgamarti** [comment]
Closing the issue because this script is deprecated.
