### ISSUE TITLE
00-set-vars.sh and show-env.sh do not work

### ISSUE THREAD

**Issue by chrfrenning** [microsoft/SmartHotel360-Backend#31]
I am having problems with 00-set-vars.sh on both Ubuntu running on Linux for Windows Subsystem and in Bash Terminal on Mac. Parameters are set and displayed correctly by 00-set-vars.sh but subsequent runs of show-vars.sh or 01-aks-create.sh fail with empty values.

**Comment by olgamarti** [comment]
Fixed in PR #34   
Please let us know if you are still experiencing the issue.
