### ISSUE TITLE
two sets of charts

### ISSUE THREAD

**Issue by bradygmsft** [microsoft/SmartHotel360-Backend#6]
We noticed there are two sets of Helm charts for the hotels API. one set is in the deploy/k8s folder, but the old set was left in the Hotels API source tree. We need to remove the ones from the source tree and to leave only the ones that remain to be those in the deploy/k8s folder. 

We **also** need to then test the dev spaces functionality to make sure the demo works as it is written. If it doesn't, we need to create other issues to reflect each of the work items that need to be created to enable dev spaces, yet have only one set of Helm files.

**Comment by bradygmsft** [comment]
@eiximenis - This is a holdover from the Helm work, as this was missed and I'm not sure the Dev Spaces functionality has been tested by the dev team. This task should be completed when there are only 1 set of Helm files for the Hotels API (and all other APIs in the back-end repo), **and** once the Dev Spaces functionality has been fully tested successfully per the demo script. Please provide an ETA on when this will be completed (testing inclusive). Thanks.

**Comment by eiximenis** [comment]
Hi @bradygmsft 
Sorry for late response, did not see that.

Helm charts were not tested with devspaces tooling. Let me see what is needed to reuse our current helm charts with devspaces.

Thx

**Comment by eiximenis** [comment]
Solved in PR #35
